/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplyCreator: typeof import('./src/components/ApplyCreator.vue')['default']
    copy: typeof import('./src/components/icons/IconUnverified copy.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTag: typeof import('element-plus/es')['ElTag']
    Home: typeof import('./src/components/icons/Home.vue')['default']
    IconBottom: typeof import('./src/components/icons/IconBottom.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconInstagram: typeof import('./src/components/icons/IconInstagram.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconOrder: typeof import('./src/components/icons/IconOrder.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconUnverified: typeof import('./src/components/icons/IconUnverified.vue')['default']
    IconVerified: typeof import('./src/components/icons/IconVerified.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBreadcurmb: typeof import('./src/components/TheBreadcurmb.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheIcon: typeof import('./src/components/TheIcon.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    ThePaths: typeof import('./src/components/ThePaths.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTodo: typeof import('./src/components/TheTodo.vue')['default']
    TheTopbar: typeof import('./src/components/TheTopbar.vue')['default']
  }
}
