/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplyCreator: typeof import('./src/components/ApplyCreator.vue')['default']
    CreatorApply: typeof import('./src/components/CreatorApply.vue')['default']
    CreatorPreview: typeof import('./src/components/CreatorPreview.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconBottom: typeof import('./src/components/icons/IconBottom.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconOrder: typeof import('./src/components/icons/IconOrder.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconRemove: typeof import('./src/components/icons/IconRemove.vue')['default']
    IconUnverified: typeof import('./src/components/icons/IconUnverified.vue')['default']
    IconVerified: typeof import('./src/components/icons/IconVerified.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialList: typeof import('./src/components/SocialList.vue')['default']
    ThePaths: typeof import('./src/components/ThePaths.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTodo: typeof import('./src/components/TheTodo.vue')['default']
    TheTopbar: typeof import('./src/components/TheTopbar.vue')['default']
  }
}
